### ISSUE TITLE
[BUG] Hotend Fan always 100%

### ISSUE THREAD

**Issue by bernhardberger** [Poket-Jony/Marlin-A4MaxPro-2.0.x#13]
With the 2.0 beta release the hotend fan doesn't shut off at times and stays at 100%.

Not entirely reproducable at all times, but I had just had it on PID Autotune, even after restarting the printer multiple times.

**Comment by Erik262** [comment]
With M107 you can power off your fans. But I think the fan wants to cool your printhead down or does it also appear on low temperature?

**Comment by bernhardberger** [comment]
I wasn't able to shut it off at all. But I think I may have found the culprit: printer off, hotend > 50°C (approx) - printer on - fan goes 100% and stays there. If I let it go down < 50° and reboot after that all is normal.

I think this really is an edge case now and can be ignored.
