### ISSUE TITLE
[FR] Adjust Filament Load/Unload lengths

### ISSUE THREAD

**Issue by bernhardberger** [Poket-Jony/Marlin-A4MaxPro-2.0.x#17]
Not sure if it makes sense, but we could potentially edit default filament load/unload lengths that make more sense than the i3 Mega values from the Bowden:

M503:
```
Filament load/unload lengths:
M603 L538.00 U555.00
```

**Comment by Poket-Jony** [comment]
#define FILAMENT_CHANGE_UNLOAD_LENGTH 100
#define FILAMENT_CHANGE_EXTRUDE_LENGTH 50

**Comment by Poket-Jony** [comment]
changed in https://github.com/Poket-Jony/Marlin-A4MaxPro-2.0.x/commit/65992f3cbdc35d5b44b8752601baad2b56b9a00b
