### ISSUE TITLE
[BUG] Printing after a finished/aborted Print sometimes don't work

### ISSUE THREAD

**Issue by Poket-Jony** [Poket-Jony/Marlin-A4MaxPro-2.0.x#2]
After some finished/aborted prints i could not print again without restarting.

Additionally i noticed if i cancel a print, the print window with all the information, shows the two main buttons (Print, Resume) in green. If you cancel one more time, they turn blue, then press back once and everything is back to normal.

**Will require further investigation!**

**Comment by Alexboyru** [comment]
Confirm. After stop printing, I cannot start a new print.

**Comment by Poket-Jony** [comment]
Should be fixed in https://github.com/Poket-Jony/Marlin-A4MaxPro-2.0.x/releases/tag/v2.1.0-dev

**Comment by Poket-Jony** [comment]
The problem still seems to exist.

**Comment by Poket-Jony** [comment]
probably fixed with https://github.com/Poket-Jony/Marlin-A4MaxPro-2.0.x/commit/0ebbe890e3acc8c5d17d8d5463753e769578ffd2
