### ISSUE TITLE
[FR] Enable Linear Advance, but set it to 0

### ISSUE THREAD

**Issue by bernhardberger** [Poket-Jony/Marlin-A4MaxPro-2.0.x#20]
I think we should enable linear advance - but set the default value to 0, thus enabling the feature but disabling LA unless a K-value is specified in the start code.

**Comment by Erik262** [comment]
Why should the linear advance feature turned off for the 4MP?

**Comment by bernhardberger** [comment]
It shouldn't. That's exactly my point.

But linear advance needs a per-filament calibration anyways - hence the suggested default value of K0

**Comment by Poket-Jony** [comment]
Merged in https://github.com/Poket-Jony/Marlin-A4MaxPro-2.0.x/pull/19
