### ISSUE TITLE
[QUESTION] Autotuning Hotend / Hotbed in special menu not working

### ISSUE THREAD

**Issue by achrainer** [Poket-Jony/Marlin-A4MaxPro-2.0.x#30]
Hi,

it seems that with the latest release, the Auto-Tune PID menu items do no longer work. The machine does not heat up anything and turns off within 1-2 minutes.

Best regards from Austria,
Gerhard

**Comment by Poket-Jony** [comment]
Please connect to the printer via Pronterface (or similar) and have a look at the output. There should be exactly what he does.

**Comment by achrainer** [comment]
Servus,

schau ich mir natürlich mal an, kein Problem. Mir ist’s nur aufgefallen, weil die ersten 2.x Versionen hier kein Problem machten. Dachte, es wäre evtl. das gesamte Special Menu nicht in Ordnung.

Wenn’s Erkenntnisse gibt, aktualisiere ich das Ticket.

LG Gerhard

(English)
Ok, I’ll have a look and update you if there is more detail

Von: Jonas Plamann <notifications@github.com>
Gesendet: Montag, 24. Februar 2020 13:45
An: Poket-Jony/Marlin-A4MaxPro-2.0.x <Marlin-A4MaxPro-2.0.x@noreply.github.com>
Cc: Gerhard Achrainer | orgacalc <ga@orgacalc.eu>; Author <author@noreply.github.com>
Betreff: Re: [Poket-Jony/Marlin-A4MaxPro-2.0.x] [BUG] Autotuning Hotend / Hotbed in special menu not working (#30)


Please connect to the printer via Pronterface (or similar) and have a look at the output. There should be exactly what he does.

**Comment by Poket-Jony** [comment]
In the last RC versions, the new shutdown M85 was added, which switches the printer off after 15 minutes of inactivity. May be that you did the PID tuning right then. It is best to deactivate "auto power off" in the status menu before do the PID Tuning.

**Comment by bernhardberger** [comment]
Works for me. Only a missing "peep"-Tone on the bed pid tuning, but worked like a charm.

**Comment by Poket-Jony** [comment]
https://github.com/Poket-Jony/Marlin-A4MaxPro-2.0.x/blob/master/Marlin/src/lcd/extensible_ui/lib/dwin/DwinTFT.cpp#L314 should produce the sound .. but the method may not be called
