### ISSUE TITLE
Change temperature menu display

### ISSUE THREAD

**Issue by Piazzi68** [Poket-Jony/Marlin-A4MaxPro-2.0.x#33]
### Feature Workflow

1. during a print the menu to change the nozzle or bed temperature does not work.

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Poket-Jony** [comment]
That is correct behavior.
