### ISSUE TITLE
[BUG] LCD Print-Time output

### ISSUE THREAD

**Issue by bernhardberger** [Poket-Jony/Marlin-A4MaxPro-2.0.x#34]
Not a breaking bug, but for the sake of documenting it:

![IMG_20200229_015223](https://user-images.githubusercontent.com/2110083/75607471-d11d4600-5af7-11ea-87c0-bdc2a1ddbe1f.jpg)

**Comment by Poket-Jony** [comment]
fixed in https://github.com/Poket-Jony/Marlin-A4MaxPro-2.0.x/commit/c2bab59874b7ac71f6c02d38b98789cbe586c071
