### ISSUE TITLE
[SOLUTION] Light flickers when printing

### ISSUE THREAD

**Issue by Erik262** [Poket-Jony/Marlin-A4MaxPro-2.0.x#9]
### Bug Description

I solved the light flickering problem by doing an hotbed Pid-tunning, even I was satisfy with my results. Fortunately I recognised flickering does no more appear after that.
Maybe it helps someone.

**Comment by Poket-Jony** [comment]
[Quote from mpk:](https://drucktipps3d.de/forum/topic/anycubic-4max-pro-marlin-1-1-9-firmware-ai3m-basierend/?part=8#postid-71702)
> LED flickering is pwm related. PID-tunning might help.
If it doesn't, try setting **SOFT_PWM_SCALE** to 3
